<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE4re0wo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE4re0wo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE4re0wo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE4re0wo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE4re0wo\App_KernelDevDebugContainer([
    'container.build_hash' => 'E4re0wo',
    'container.build_id' => '8c8c6f4d',
    'container.build_time' => 1698330572,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE4re0wo');
